export const ERROR_CODES = {
  // User related errors
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  NOT_FOUND: 'NOT_FOUND',
  CANNOT_DELETE_LAST_ADMIN: 'CANNOT_DELETE_LAST_ADMIN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  CONFLICT: 'CONFLICT',
  
  // Role related errors
  ROLES_NOT_FOUND: 'ROLES_NOT_FOUND',
  
  // Authentication errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  
  // Validation errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  
  // General errors
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE'
};

// This file defines error codes and their corresponding HTTP status codes
export const ERROR_CODE_TO_HTTP = {
  [ERROR_CODES.ALREADY_EXISTS]: 409, // Conflict
  [ERROR_CODES.CONFLICT]: 409, // Conflict
  [ERROR_CODES.NOT_FOUND]: 404, // Not Found
  [ERROR_CODES.CANNOT_DELETE_LAST_ADMIN]: 400, // Bad Request
  [ERROR_CODES.INVALID_CREDENTIALS]: 401, // Unauthorized
  [ERROR_CODES.ROLES_NOT_FOUND]: 404, // Not Found
  [ERROR_CODES.UNAUTHORIZED]: 401, // Unauthorized
  [ERROR_CODES.FORBIDDEN]: 403, // Forbidden
  [ERROR_CODES.VALIDATION_ERROR]: 400, // Bad Request
  [ERROR_CODES.BAD_REQUEST]: 400, // Bad Request
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: 500, // Internal Server Error
  [ERROR_CODES.NOT_IMPLEMENTED]: 501, // Not Implemented
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503, // Service Unavailable
};